# Project
version=1.1.0
group=com.evandev.shutterup
java_version=17

# Common
minecraft_version=1.20.1
mod_name=ShutterUp
mod_author=evanbones
mod_id=shutterup
license=Custom
credits=Shutter models/textures created by kayla_the_bee
description=A mod that adds classy decorative shutters to your world!
minecraft_version_range=[1.20.1, 1.20.2)

# Parchment
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Optional Dependencies
moonlight_version=1.20-2.16.19
every_compat_version=1.20-2.9.13
emi_version=1.1.22+1.20.1

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false