plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id "com.matthewprenger.cursegradle" version "1.4.0"
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = at
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }
}

dependencies {
    // Every Compat
    modImplementation "maven.modrinth:moonlight:${moonlight_version}-forge"
    modImplementation "maven.modrinth:every-compat:${every_compat_version}-forge"

    // EMI
    modImplementation "dev.emi:emi-forge:${emi_version}"

    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
}

jar {
    finalizedBy('reobfJar')
}

curseforge {
    apiKey = System.getenv("CURSEFORGE_TOKEN") ?: "0"
    project {
        id = "1420451"
        releaseType = "release"
        changelog = file('../CHANGELOG.md')
        changelogType = 'markdown'

        addGameVersion "1.20.1"
        addGameVersion "Java 17"
        addGameVersion "Forge"

        mainArtifact(jar) {
            displayName = "Shutter Up Forge ${project.minecraft_version} - ${project.version}"
        }

        relations {
            optionalDependency "every-compat"
            optionalDependency "vanillabackport"
        }
    }
}