plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

neoForge {
    neoFormVersion = neo_form_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'

    // Every Compat
    compileOnly "maven.modrinth:moonlight:${moonlight_version}-neoforge"
    compileOnly "maven.modrinth:every-compat:${every_compat_version}-neoforge"

    // Vanilla Backport
    compileOnly "maven.modrinth:vanillabackport:${vanillabackport_version}"
    runtimeOnly "maven.modrinth:vanillabackport:${vanillabackport_version}"
}

sourceSets.main.resources.srcDir 'src/main/generated'

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile

    sourceSets.main.resources.sourceDirectories.each { dir ->
        commonResources dir
    }
}